server:
  port: 8182

spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/db_bycoders
    username: root
    password:
  jpa:
    hibernate.ddl-auto: create
    database-platform: org.hibernate.dialect.MySQL57Dialect
    generate-ddl: true
    show-sql: true

